# fly.toml app configuration file for backend
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "blunr-backend"
primary_region = "lhr"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[env]
  PORT = "5000"
  NODE_ENV = "production"


[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']


[[vm]]
  memory = '16gb'
  cpu_kind = 'performance'
  cpus = 4
