export const ROUTES = {
  LOGIN: '/login',
  SIGNUP: '/signup',
  FORGET_PASSWORD: '/forget-password',
  RESET_PASSWORD: 'reset-password',
  POSTS: '/posts',
  CREATE_POSTS: '/new-post',
  PROFILE: '/profile',
  INBOX: '/inbox',
  SUBSCRIBED_ACCOUNT: '/subscribed-account',
  YOUR_TRANSACTIONS: '/your-transactions',
  SET_SUBSCRIPTION_PLAN: '/set-subscription-plan',
  RAISE_WITHDRWAL_REQUEST: '/raise-withdrwal-request',
  SUCCESS: '/success',
  FAILED: '/failed',
  TOP_CREATORS: '/top-creators',
  CONTACT_SUPPORT: '/contact-support',
  TERMS_AND_CONDITIONS: '/terms-of-service',
  PRIVACY_POLICY: '/privacy-policy',
};
